import { BaseAgent, safeParse, type TaskPlan } from './agent'

export interface CodeProposal {
  filePath: string
  content: string
  description: string
}

export class DeveloperAgent extends BaseAgent {
  protected async doExecute(input: string): Promise<unknown> {
    const plan = safeParse<TaskPlan>(input, { summary: '', steps: [] })
    const proposals: CodeProposal[] = plan.steps.map((step, i) => ({
      filePath: step.filePath ?? `generated_${i}.ts`,
      content: `// Generated by DeveloperAgent\n// ${step.description}\n\nexport function generatedFunction_${i}() {\n  // TODO: implement\n}\n`,
      description: step.description,
    }))
    return proposals
  }

  parseProposals(raw: string): CodeProposal[] {
    return safeParse<CodeProposal[]>(raw, [])
  }
}

export function extractCodeBlocks(text: string): CodeProposal[] {
  const proposals: CodeProposal[] = []
  const regex = /<file\s+path="([^"]+)"\s*>([\s\S]*?)<\/file\s*>/gi
  let match
  while ((match = regex.exec(text)) !== null) {
    proposals.push({ filePath: match[1], content: match[2].trim(), description: '' })
  }
  if (proposals.length === 0) {
    const blockRegex = /```(\w+)?\n([\s\S]*?)```/g
    while ((match = blockRegex.exec(text)) !== null) {
      proposals.push({ filePath: `file_${proposals.length}.${match[1] ?? 'ts'}`, content: match[2].trim(), description: '' })
    }
  }
  return proposals
}
